debug:
	go run -mod vendor cmd/example/main.go

lambda:
	if test -f main; then rm -f main; fi
	if test -f example.zip; then rm -f example.zip; fi
	GOOS=linux go build -mod vendor -o main cmd/example/main.go
	zip example.zip main
	rm -f main

docker:
	docker build -t sfomuseum-sweater-server .	

# jf: https://github.com/aaronland/go-json-tools
# copy/paste in to templates/html/common_footer.html

config:
	jf -input static/javascript/config.pruned.json -output -

js:
	@make js-sfom
	@make js-deps

js-sfom:
	echo "// This file was generated by robots\n\n" > static/javascript/sfomuseum.sweater.js
	echo "window.addEventListener('load', function(e){\n\n" >> static/javascript/sfomuseum.sweater.js
	echo "// js_WQHdplyrlQfKdHIPVZKrk2a-733sZNBYZPC_xRA5baU.pruned.js\n\n" >> static/javascript/sfomuseum.sweater.js
	cat static/javascript/js_WQHdplyrlQfKdHIPVZKrk2a-733sZNBYZPC_xRA5baU.pruned.js >> static/javascript/sfomuseum.sweater.js
	echo "\n" >> static/javascript/sfomuseum.sweater.js 
	echo "// js_J4lAocQOE0MG-pYudi5Xv0k0kjsq69AV9GOSU4WkrX0.pruned.js\n\n" >> static/javascript/sfomuseum.sweater.js
	cat static/javascript/js_J4lAocQOE0MG-pYudi5Xv0k0kjsq69AV9GOSU4WkrX0.pruned.js >> static/javascript/sfomuseum.sweater.js
	echo "\n" >> static/javascript/sfomuseum.sweater.js 
	echo "// js_-CPIpBjXzxABQv31RXcqizSgaLzthEF_xbzTZvR1Nak.pruned.js\n\n" >> static/javascript/sfomuseum.sweater.js
	cat static/javascript/js_-CPIpBjXzxABQv31RXcqizSgaLzthEF_xbzTZvR1Nak.pruned.js >> static/javascript/sfomuseum.sweater.js
	echo "\n" >> static/javascript/sfomuseum.sweater.js 
	echo "});" >> static/javascript/sfomuseum.sweater.js

js-deps:
	echo "// This file was generated by robots\n\n" > static/javascript/sfomuseum.sweater.deps.js
	echo "// jquery-3.6.0.min.js\n\n" >> static/javascript/sfomuseum.sweater.deps.js
	cat static/javascript/jquery-3.6.0.min.js >> static/javascript/sfomuseum.sweater.deps.js
	echo "// jquery.once.min.js\n\n" >> static/javascript/sfomuseum.sweater.deps.js
	cat static/javascript/jquery.once.min.js >> static/javascript/sfomuseum.sweater.deps.js
	echo "// superfish.min.js\n\n" >> static/javascript/sfomuseum.sweater.deps.js
	cat static/javascript/superfish.min.js >> static/javascript/sfomuseum.sweater.deps.js

css:
	echo "// This file was generated by robots\n\n" > static/css/sfomuseum.sweater.css
	echo "// css_tYMnZJENio3fbqTvIRK7wb8dpGIx2TaK1n--M2StjfQ.pruned.css\n\n" >> static/css/sfomuseum.sweater.css
	cat static/css/css_tYMnZJENio3fbqTvIRK7wb8dpGIx2TaK1n--M2StjfQ.pruned.css >> static/css/sfomuseum.sweater.css
	echo "\n" >> static/css/sfomuseum.sweater.css 
	echo "// sfomuseum.org.social.pruned.css\n\n" >> static/css/sfomuseum.sweater.css
	cat static/css/sfomuseum.org.social.pruned.css >> static/css/sfomuseum.sweater.css
	echo "\n" >> static/css/sfomuseum.sweater.css 
	echo "// sfomuseum.org.bootstrap.css\n\n" >> static/css/sfomuseum.sweater.css
	cat static/css/sfomuseum.org.bootstrap.css >> static/css/sfomuseum.sweater.css
